//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFramework.Kinect.VisualStudio.DebuggerVisualizers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyFramework.Kinect.VisualStudio.DebuggerVisualizers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect BodyFrame 2D visualizer.
        /// </summary>
        internal static string Body2DFrameDialogDebuggerVisualizer {
            get {
                return ResourceManager.GetString("Body2DFrameDialogDebuggerVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect BodyFrame 2D visualizer, only image.
        /// </summary>
        internal static string Body2DFrameImageDialogDebuggerVisualizer {
            get {
                return ResourceManager.GetString("Body2DFrameImageDialogDebuggerVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect BodyIndexFrame 2D visualizer.
        /// </summary>
        internal static string BodyIndexFrameDialogDebuggerVisualizer {
            get {
                return ResourceManager.GetString("BodyIndexFrameDialogDebuggerVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect BodyIndexFrame 2D visualizer, only image.
        /// </summary>
        internal static string BodyIndexFrameImageDialogDebuggerVisualizer {
            get {
                return ResourceManager.GetString("BodyIndexFrameImageDialogDebuggerVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect ColorFrame 2D visualizer.
        /// </summary>
        internal static string ColorFrameDialogDebuggerVisualizer {
            get {
                return ResourceManager.GetString("ColorFrameDialogDebuggerVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect ColorFrame 2D visualizer, only image.
        /// </summary>
        internal static string ColorFrameImageDialogDebuggerVisualizer {
            get {
                return ResourceManager.GetString("ColorFrameImageDialogDebuggerVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect DepthFrame 2D visualizer.
        /// </summary>
        internal static string DepthFrameDialogDebuggerVisualizer {
            get {
                return ResourceManager.GetString("DepthFrameDialogDebuggerVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect DepthFrame 2D visualizer, only image.
        /// </summary>
        internal static string DepthFrameImageDialogDebuggerVisualizer {
            get {
                return ResourceManager.GetString("DepthFrameImageDialogDebuggerVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect FaceFrame 2D visualizer.
        /// </summary>
        internal static string FaceFrameDialogDebuggerVisualizer {
            get {
                return ResourceManager.GetString("FaceFrameDialogDebuggerVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect FaceFrame 2D visualizer, only image.
        /// </summary>
        internal static string FaceFrameImageDialogDebuggerVisualizer {
            get {
                return ResourceManager.GetString("FaceFrameImageDialogDebuggerVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect HighDefinitionFaceFrame 2D visualizer.
        /// </summary>
        internal static string HighDefinitionFaceFrameDialogDebuggerVisualizer {
            get {
                return ResourceManager.GetString("HighDefinitionFaceFrameDialogDebuggerVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect HighDefinitionFaceFrame 2D visualizer, only image.
        /// </summary>
        internal static string HighDefinitionFaceFrameImageDialogDebuggerVisualizer {
            get {
                return ResourceManager.GetString("HighDefinitionFaceFrameImageDialogDebuggerVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect InfraredFrame 2D visualizer.
        /// </summary>
        internal static string InfraredFrameDialogDebuggerVisualizer {
            get {
                return ResourceManager.GetString("InfraredFrameDialogDebuggerVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect InfraredFrame 2D visualizer, only image.
        /// </summary>
        internal static string InfraredFrameImageDialogDebuggerVisualizer {
            get {
                return ResourceManager.GetString("InfraredFrameImageDialogDebuggerVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect LongExposureInfraredFrame 2D visualizer.
        /// </summary>
        internal static string LongExposureInfraredFrameDialogDebuggerVisualizer {
            get {
                return ResourceManager.GetString("LongExposureInfraredFrameDialogDebuggerVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect LongExposureInfraredFrame 2D visualizer, only image.
        /// </summary>
        internal static string LongExposureInfraredFrameImageDialogDebuggerVisualizer {
            get {
                return ResourceManager.GetString("LongExposureInfraredFrameImageDialogDebuggerVisualizer", resourceCulture);
            }
        }
    }
}
